version: "3.7"

services:
  screego:
    image: ghcr.io/screego/server:1.10.3
    container_name: screego
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - /opt/screego/.users:/opt/screego/.users
      - /opt/screego/server.config:/etc/screego/server.config
